# Generated by Django 5.0.1 on 2024-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookImage', models.URLField()),
                ('bookTitle', models.CharField(max_length=250, null=True)),
                ('bookAuthors', models.CharField(max_length=250, null=True)),
                ('bookDesc', models.TextField(default='')),
            ],
        ),
    ]
